#!/bin/bash
source common/begin
source common/resizecons
export NEWT_COLORS='
root=,brown
window=,lightgray
border=white,lightgray
textbox=white,blue
button=black,white
actbutton=black,white
title=black,lightgray
'
qmenutheme () {
qmenu=$(TERM=ansi whiptail --title "-=- Q4OS Seb Scripts -=-" --menu "                Qtheme Script - choose an option:" 25 70 15 " Light" "   [     Classic windows 10 theme    ]" " Dark" "   [       Dark windows 10 theme     ]" " return" "   [    <- return to previous menu   ]" 3>&1 1>&2 2>&3)

case $qmenu in
" Light")   
clear
./qtheme.sh
if [ $? -eq 2 ]; then return 0; else exit
fi
;;
" Dark")   
clear
./qtheme.sh -d
if [ $? -eq 2 ]; then return 0; else exit
fi
;;
" return") return 0
;;
esac
}

byebye () {
echo -e "                                      ${LIGHTGREEN}^-^"
echo -e "                                     (o O)${GRAY}"
echo -e "                               ══${LIGHTGREEN}ooO${GRAY}══${LIGHTGREEN}(_)${GRAY}══${LIGHTGREEN}Ooo${GRAY}══════ ${NOCOLOR}Bye Bye ! ${GRAY}════════${NOCOLOR}"
exit
}
deskfold=$(xdg-user-dir DESKTOP)

while [ 1 ]
do
wmctrl -r :ACTIVE: -N "-=- Q4OS Seb Scripts -=-   Main menu"
options=(
    " Qtheme" "   [      Theming « ala windows 10 »    ]"
    " Qperf" "   [        Improve performances        ]"
    " Qlaptop" "   [    Laptop specific configuration   ]"
    " Qapps" "   [    Install selected applications   ]"
    " Qtools" "   [  Customize theme,system & more...  ]"
    " " " "
)

if [ ! -e "$deskfold/Q4OS seb Scripts.desktop" ]; then
options+=(" ~Create shortcut" "   [Create desktop shortcut for easy run]")
fi

options+=(" ~Info~" "   [          Display README.md         ]"
          " exit" "   [       <- quit this menu (Esc)      ]"
)

menu=()
for ((i = 0; i < ${#options[@]}; i+=2)); do
    menu+=("${options[i]}" "${options[i + 1]}")
done

ret=$(TERM=ansi whiptail --title "-=- Q4OS Seb Scripts -=-" --menu "Choose a script to launch:" 25 70 15 "${menu[@]}" --cancel-button "Exit" 3>&1 1>&2 2>&3)





          

echo
case $ret in
" Qtheme")   
	qmenutheme
;;
" Qperf")   
	clear
	./qperf.sh
	if [ $? -eq 2 ]; then return 0; else exit
	fi
;;
" Qlaptop")   
	clear
	./qlaptop.sh
	if [ $? -eq 2 ]; then return 0; else exit
	fi
;;
" Qapps")   
	clear
	./qapps.sh
	return 0
;;
" Qtools")   
	clear
	./qtools.sh
	return 0
;;
" ~Create shortcut")
clear
SCRIPT_PATH="$(readlink -f "$0")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
CURRENT_USER=$(whoami)
\cp "common/shortcut.desktop" "$deskfold/Q4OS seb Scripts.desktop"
sed -i "s|XxXxXxXx|$SCRIPT_DIR|g" "$deskfold/Q4OS seb Scripts.desktop"
sudo chown "$CURRENT_USER:$CURRENT_USER" "$deskfold/Q4OS seb Scripts.desktop"
echo Done.
read -p "Press enter..."
return 0
;;
" ~Info~")   
whiptail --title "-=- Q4OS Seb Scripts -=-" --msgbox "`cat README.md`" --ok-button "ESC to return" --scrolltext 30 85
	return 0
;;
" exit") 
byebye
;;
" ")
;;
*)
byebye
;;

esac
done