#!/bin/sh

#check root
if [ "$(id -u)" -ne 0 ]; then
        echo 'This script must be run by root' >&2
        exit 1
fi
#


USER_HOME=$(eval echo ~${SUDO_USER})


NOCOLOR='\033[0m'
RED='\033[0;31m'
ORANGE='\033[0;33m'
BLUE='\033[0;96m'
SEPL="${ORANGE}════════════════════════════════════════════════════════════════════════════════════════${NOCOLOR}"
echo "${RED}== ${BLUE}\e[1m\e[4mCopying various files...\e[21m"
echo "${SEPL}"
echo "  \e[35m░▒▓█\033[0m copying icons"
if [ $1 -eq 1 ]
then
iconth="dark"
else
iconth="light"
fi
rm -fr /usr/share/icons/kdeten_$iconth
mkdir -p /usr/share/icons/kdeten_$iconth
#tar -xzf kdeten_icons.tar.gz -C /usr/share/icons/kdeten_light/
7z x -so kdeten_icons.tar.7z | tar xf - -C /usr/share/icons/kdeten_$iconth/
tar -xzf kdeten_mods_$iconth.tar.gz -C /usr/share/icons/kdeten_$iconth/
#links
cd /usr/share/icons/kdeten_$iconth/
ln -s kde1.png 16x16/actions/kde2.png
ln -s kde1.png 16x16/actions/kde3.png
ln -s kde1.png 16x16/actions/kde4.png
ln -s kde1.png 16x16/actions/kde5.png
ln -s kde1.png 16x16/actions/kde6.png
ln -s kde1.png 22x22/actions/kde2.png
ln -s kde1.png 22x22/actions/kde3.png
ln -s kde1.png 22x22/actions/kde4.png
ln -s kde1.png 22x22/actions/kde5.png
ln -s kde1.png 22x22/actions/kde6.png
ln -s kde1.png 24x24/actions/kde2.png
ln -s kde1.png 24x24/actions/kde3.png
ln -s kde1.png 24x24/actions/kde4.png
ln -s kde1.png 24x24/actions/kde5.png
ln -s kde1.png 24x24/actions/kde6.png
ln -s kde1.png 32x32/actions/kde2.png
ln -s kde1.png 32x32/actions/kde3.png
ln -s kde1.png 32x32/actions/kde4.png
ln -s kde1.png 32x32/actions/kde5.png
ln -s kde1.png 32x32/actions/kde6.png
ln -s kde1.png 48x48/actions/kde2.png
ln -s kde1.png 48x48/actions/kde3.png
ln -s kde1.png 48x48/actions/kde4.png
ln -s kde1.png 48x48/actions/kde5.png
ln -s kde1.png 48x48/actions/kde6.png
ln -s kde1.png 64x64/actions/kde2.png
ln -s kde1.png 64x64/actions/kde3.png
ln -s kde1.png 64x64/actions/kde4.png
ln -s kde1.png 64x64/actions/kde5.png
ln -s kde1.png 64x64/actions/kde6.png
ln -s text-x-generic.png 16x16/mimetypes/text-x-log.png
ln -s text-x-generic.png 22x22/mimetypes/text-x-log.png
ln -s text-x-generic.png 24x24/mimetypes/text-x-log.png
ln -s text-x-generic.png 32x32/mimetypes/text-x-log.png
ln -s text-x-generic.png 48x48/mimetypes/text-x-log.png
ln -s text-x-generic.png 64x64/mimetypes/text-x-log.png
ln -s edit-select-all.png 16x16/actions/kr_selectall.png
ln -s edit-select-all.png 22x22/actions/kr_selectall.png
ln -s edit-select-all.png 24x24/actions/kr_selectall.png
ln -s edit-select-all.png 32x32/actions/kr_selectall.png
ln -s edit-select-all.png 48x48/actions/kr_selectall.png
ln -s edit-select-all.png 64x64/actions/kr_selectall.png
ln -s edit-select-none.png 16x16/actions/kr_unselectall.png
ln -s edit-select-none.png 22x22/actions/kr_unselectall.png
ln -s edit-select-none.png 24x24/actions/kr_unselectall.png
ln -s edit-select-none.png 32x32/actions/kr_unselectall.png
ln -s edit-select-none.png 48x48/actions/kr_unselectall.png
ln -s edit-select-none.png 64x64/actions/kr_unselectall.png
ln -s edit-select.png 16x16/actions/kr_select.png
ln -s edit-select.png 22x22/actions/kr_select.png
ln -s edit-select.png 24x24/actions/kr_select.png
ln -s edit-select.png 32x32/actions/kr_select.png
ln -s edit-select.png 48x48/actions/kr_select.png
ln -s edit-select.png 64x64/actions/kr_select.png
ln -s edit-select-invert.png 16x16/actions/kr_invert.png
ln -s edit-select-invert.png 22x22/actions/kr_invert.png
ln -s edit-select-invert.png 24x24/actions/kr_invert.png
ln -s edit-select-invert.png 32x32/actions/kr_invert.png
ln -s edit-select-invert.png 48x48/actions/kr_invert.png
ln -s edit-select-invert.png 64x64/actions/kr_invert.png
ln -s nm_device_wired.png 16x16/actions/connect_creating.png
ln -s nm_device_wired.png 16x16/actions/connect_established.png
ln -s nm_device_wired.png 22x22/actions/connect_creating.png
ln -s nm_device_wired.png 22x22/actions/connect_established.png
ln -s nm_device_wired.png 24x24/actions/connect_creating.png
ln -s nm_device_wired.png 24x24/actions/connect_established.png
ln -s nm_device_wired.png 32x32/actions/connect_creating.png
ln -s nm_device_wired.png 32x32/actions/connect_established.png
ln -s nm_device_wired.png 48x48/actions/connect_creating.png
ln -s nm_device_wired.png 48x48/actions/connect_established.png
ln -s nm_device_wired.png 64x64/actions/connect_creating.png
ln -s nm_device_wired.png 64x64/actions/connect_established.png
ln -s edit-clear-locationbar-ltr.png 16x16/actions/locationbar_erase.png
ln -s edit-clear-locationbar-ltr.png 22x22/actions/locationbar_erase.png
ln -s edit-clear-locationbar-ltr.png 24x24/actions/locationbar_erase.png
ln -s edit-clear-locationbar-ltr.png 32x32/actions/locationbar_erase.png
ln -s edit-clear-locationbar-ltr.png 48x48/actions/locationbar_erase.png
ln -s edit-clear-locationbar-ltr.png 64x64/actions/locationbar_erase.png
ln -s ../../16x16/actions/edit-paste.png 16x16/apps/klipper.png
ln -s ../../22x22/actions/edit-paste.png 22x22/apps/klipper.png
ln -s ../../24x24/actions/edit-paste.png 24x24/apps/klipper.png
ln -s ../../32x32/actions/edit-paste.png 32x32/apps/klipper.png
ln -s ../../48x48/actions/edit-paste.png 48x48/apps/klipper.png
ln -s kcalc.png 16x16/apps/calc.png
ln -s kcalc.png 22x22/apps/calc.png
ln -s kcalc.png 24x24/apps/calc.png
ln -s kcalc.png 32x32/apps/calc.png
ln -s kcalc.png 48x48/apps/calc.png
ln -s kcalc.png 64x64/apps/calc.png
ln -s kwrite.png 16x16/apps/notepad.png
ln -s kwrite.png 22x22/apps/notepad.png
ln -s ksysguard.png 16x16/apps/taskmgr.png
ln -s ksysguard.png 22x22/apps/taskmgr.png
ln -s ksysguard.png 24x24/apps/taskmgr.png
ln -s ksysguard.png 32x32/apps/taskmgr.png
ln -s ksysguard.png 48x48/apps/taskmgr.png
ln -s ksysguard.png 64x64/apps/taskmgr.png
ln -s kolourpaint.svg 64x64/apps/paint.svg
ln -s konsole.png 16x16/apps/cmd.png
ln -s konsole.png 22x22/apps/cmd.png
ln -s konsole.png 24x24/apps/cmd.png
ln -s konsole.png 32x32/apps/cmd.png
ln -s konsole.png 48x48/apps/cmd.png
ln -s konsole.png 64x64/apps/cmd.png
ln -s ksnapshot.svg 64x64/apps/snapshot.svg
ln -s ../../scalable/actions/kfind.png 16x16/actions/kfind.png
ln -s ../../scalable/actions/kfind.png 22x22/actions/kfind.png
ln -s ../../scalable/actions/kfind.png 24x24/actions/kfind.png
ln -s ../../scalable/actions/kfind.png 32x32/actions/kfind.png
ln -s ../../scalable/actions/kfind.png 48x48/actions/kfind.png
ln -s ../../scalable/actions/kfind.png 64x64/actions/kfind.png
ln -s unlock.png 16x16/actions/kdenlive-unlock.png
ln -s unlock.png 22x22/actions/kdenlive-unlock.png
ln -s unlock.png 24x24/actions/kdenlive-unlock.png
ln -s unlock.png 16x16/actions/object-unlocked.png
ln -s unlock.png 22x22/actions/object-unlocked.png
ln -s unlock.png 24x24/actions/object-unlocked.png
ln -s unlock.png 16x16/actions/document-decrypt.png
ln -s unlock.png 22x22/actions/document-decrypt.png
ln -s unlock.png 24x24/actions/document-decrypt.png
ln -s document-properties.png 16x16/actions/gtk-properties.png
ln -s document-properties.png 22x22/actions/gtk-properties.png
ln -s document-properties.png 24x24/actions/gtk-properties.png
ln -s document-properties.png 32x32/actions/gtk-properties.png
ln -s document-properties.png 48x48/actions/gtk-properties.png
ln -s document-properties.png 64x64/actions/gtk-properties.png
ln -s document-properties.png 16x16/actions/info.png
ln -s document-properties.png 22x22/actions/info.png
ln -s document-properties.png 24x24/actions/info.png
ln -s document-properties.png 32x32/actions/info.png
ln -s document-properties.png 48x48/actions/info.png
ln -s document-properties.png 64x64/actions/info.png
ln -s ../../16x16/actions/document-properties.png 16x16/mimetypes/info.png
ln -s ../../22x22/actions/document-properties.png 22x22/mimetypes/info.png
ln -s ../../24x24/actions/document-properties.png 24x24/mimetypes/info.png
ln -s ../../32x32/actions/document-properties.png 32x32/mimetypes/info.png
ln -s ../../48x48/actions/document-properties.png 48x48/mimetypes/info.png
ln -s ../../64x64/actions/document-properties.png 48x48/mimetypes/info.png
ln -s run.png 16x16/actions/gtk-execute.png
ln -s run.png 22x22/actions/gtk-execute.png
ln -s run.png 24x24/actions/gtk-execute.png
ln -s run.png 32x32/actions/gtk-execute.png
ln -s run.png 48x48/actions/gtk-execute.png
ln -s run.png 64x64/actions/gtk-execute.png
#ln -s ../../16x16/apps/ksysguard.png 16x16/actions/fork.png
#ln -s ../../16x16/apps/ksysguard.png 22x22/actions/fork.png
#ln -s ../../16x16/apps/ksysguard.png 24x24/actions/fork.png
cd - > /dev/null 2>&1
#
sudo sed -i "/Name=kde_ten/c\Name=kdeten_$iconth" /usr/share/icons/kdeten_$iconth/index.theme
gtk-update-icon-cache /usr/share/icons/kdeten_$iconth/
echo "  \e[35m░▒▓█\033[0m copying cursors"
rm -fr /usr/share/icons/Windows10Dark
rm -fr /usr/share/icons/Windows10Light
tar -xzf Windows10Light.tar.gz -C /usr/share/icons/
tar -xzf Windows10Dark.tar.gz -C /usr/share/icons/
create_links() {
cd $1
ln -s half-busy 00000000000000020006000e7e9ffc3f > /dev/null 2>&1
ln -s half-busy 08e8e1c95fe2fc01f976f1e063a24ccd > /dev/null 2>&1
ln -s half-busy 3ecb610c1bf2410f44200f48c40d3599 > /dev/null 2>&1
ln -s half-busy left_ptr_watch > /dev/null 2>&1
ln -s half-busy progress > /dev/null 2>&1
ln -s half-busy work > /dev/null 2>&1
ln -s size_ver 00008160000006810000408080010102 > /dev/null 2>&1
ln -s circle 03b6e0fcb3499374a867c041f52298f0 > /dev/null 2>&1
ln -s circle crossed_circle > /dev/null 2>&1
ln -s circle dnd-no-drop > /dev/null 2>&1
ln -s circle forbidden > /dev/null 2>&1
ln -s circle no-drop > /dev/null 2>&1
ln -s circle not-allowed > /dev/null 2>&1
ln -s circle pirate > /dev/null 2>&1
ln -s circle unavailiable > /dev/null 2>&1
ln -s dnd-move 4498f0e0c1937ffe01fd06f973665830 > /dev/null 2>&1
ln -s dnd-move 9081237383d90e509aa00f00170e968f > /dev/null 2>&1
ln -s dnd-move fcf21c00b30f7e3f83fe0dfd12e71cff > /dev/null 2>&1
ln -s dnd-move all-scroll > /dev/null 2>&1
ln -s dnd-move closedhand > /dev/null 2>&1
ln -s dnd-move dnd-none > /dev/null 2>&1
ln -s dnd-move fleur > /dev/null 2>&1
ln -s dnd-move grab > /dev/null 2>&1
ln -s dnd-move grabbing > /dev/null 2>&1
ln -s dnd-move move > /dev/null 2>&1
ln -s dnd-move size_all > /dev/null 2>&1
ln -s default 1081e37283d90000800003c07f3ef6bf > /dev/null 2>&1
ln -s default 6407b0e94181790501fd1e167b474872 > /dev/null 2>&1
ln -s default b66166c04f8c3109214a4fbd64a50fc8 > /dev/null 2>&1
ln -s default 3085a0e285430894940527032f8b26df > /dev/null 2>&1
ln -s default 640fb0e74195791501fd1ed57b41487f > /dev/null 2>&1
ln -s default a2a266d0498c3104214a47bd64ab0fc8 > /dev/null 2>&1
ln -s default x-cursor > /dev/null 2>&1
ln -s default wayland-cursor > /dev/null 2>&1
ln -s default context-menu > /dev/null 2>&1
ln -s default alias > /dev/null 2>&1
ln -s default copy > /dev/null 2>&1
ln -s default left_ptr > /dev/null 2>&1
ln -s default arrow > /dev/null 2>&1
ln -s default top_left_arrow > /dev/null 2>&1
ln -s default size-ver > /dev/null 2>&1
ln -s default size-hor > /dev/null 2>&1
ln -s default size-fdiag > /dev/null 2>&1
ln -s default size-bdiag > /dev/null 2>&1
ln -s default right_ptr > /dev/null 2>&1
ln -s default plus > /dev/null 2>&1
ln -s default openhand > /dev/null 2>&1
ln -s default dnd-copy > /dev/null 2>&1
ln -s cross crosshair > /dev/null 2>&1
ln -s pencil cell > /dev/null 2>&1
ln -s pencil hand > /dev/null 2>&1
ln -s pencil draft > /dev/null 2>&1
ln -s pointer 9d800788f1b08800ae810202380a0822 > /dev/null 2>&1
ln -s pointer e29285e634086352946a0e7090d73106 > /dev/null 2>&1
ln -s pointer hand1 > /dev/null 2>&1
ln -s pointer hand2 > /dev/null 2>&1
ln -s pointer link > /dev/null 2>&1
ln -s pointer pointing_hand > /dev/null 2>&1
ln -s help question_arrow > /dev/null 2>&1
ln -s help left_ptr_help > /dev/null 2>&1
ln -s help whats_this > /dev/null 2>&1
ln -s top_right_corner sw-resize > /dev/null 2>&1
ln -s top_right_corner size_bdiag > /dev/null 2>&1
ln -s top_right_corner nesw-resize > /dev/null 2>&1
ln -s top_right_corner ne-resize > /dev/null 2>&1
ln -s top_right_corner dgn2 > /dev/null 2>&1
ln -s top_right_corner bottom_left_corner > /dev/null 2>&1
ln -s top_left_corner size_fdiag > /dev/null 2>&1
ln -s top_left_corner se-resize > /dev/null 2>&1
ln -s top_left_corner nwse-resize > /dev/null 2>&1
ln -s top_left_corner nw-resize > /dev/null 2>&1
ln -s top_left_corner dgn1 > /dev/null 2>&1
ln -s top_left_corner bottom_right_corner > /dev/null 2>&1
ln -s vert v_double_arrow > /dev/null 2>&1
ln -s vert top_side > /dev/null 2>&1
ln -s vert s-resize > /dev/null 2>&1
ln -s vert split_v > /dev/null 2>&1
ln -s vert size_ver > /dev/null 2>&1
ln -s vert sb_v_double_arrow > /dev/null 2>&1
ln -s vert row-resize > /dev/null 2>&1
ln -s vert ns-resize > /dev/null 2>&1
ln -s vert n-resize > /dev/null 2>&1
ln -s vert down-arrow > /dev/null 2>&1
ln -s vert bottom_side > /dev/null 2>&1
ln -s size_hor w-resize > /dev/null 2>&1
ln -s size_hor split_h > /dev/null 2>&1
ln -s size_hor sb_h_double_arrow > /dev/null 2>&1
ln -s size_hor right_side > /dev/null 2>&1
ln -s size_hor right-arrow > /dev/null 2>&1
ln -s size_hor left-arrow > /dev/null 2>&1
ln -s size_hor left_side > /dev/null 2>&1
ln -s size_hor horz > /dev/null 2>&1
ln -s size_hor h_double_arrow > /dev/null 2>&1
ln -s size_hor ew-resize > /dev/null 2>&1
ln -s size_hor e-resize > /dev/null 2>&1
ln -s size_hor col-resize > /dev/null 2>&1
ln -s help 5c6cd98b3f3ebcb1f9c7f1c204630408 > /dev/null 2>&1
ln -s help d9ce0ab605698f320427677b458ad60b > /dev/null 2>&1
ln -s busy wait > /dev/null 2>&1
ln -s busy watch > /dev/null 2>&1
ln -s up-arrow center_ptr > /dev/null 2>&1
ln -s up-arrow alternate > /dev/null 2>&1
ln -s text xterm > /dev/null 2>&1
ln -s text vertical-text > /dev/null 2>&1
ln -s text ibeam > /dev/null 2>&1
cd - > /dev/null 2>&1
}
create_links /usr/share/icons/Windows10Light/cursors
create_links /usr/share/icons/Windows10Dark/cursors

echo "  \e[35m░▒▓█\033[0m copying start menu images"
if [ $1 -eq 1 ]
then
tar -xzf StartHere.png-dark.tar.gz -C /usr/share/pixmaps/
else
tar -xzf StartHere.png.tar.gz -C /usr/share/pixmaps/
fi
\cp StartHere_color.png /usr/share/pixmaps/

# echo "  \e[35m░▒▓█\033[0m copying kmenu side image"
# if [ $1 -eq 1 ]
# then
# tar -xzf kside-dark.tar.gz -C /opt/trinity/share/apps/kicker/pics/
# else
# tar -xzf kside.tar.gz -C /opt/trinity/share/apps/kicker/pics/
# fi

echo "  \e[35m░▒▓█\033[0m copying wallpapers"
tar -xzf q4seb_wallpapers.tar.gz -C /opt/trinity/share/wallpapers/

echo "  \e[35m░▒▓█\033[0m copying font"
#tar -xzf Segoe_UI.tar.gz -C /usr/share/fonts/truetype/
#tar -xzf consolas.tar.gz -C /usr/share/fonts/truetype/
7z x -so Segoe_UI.tar.7z | tar xf - -C /usr/share/fonts/truetype/
7z x -so consolas.tar.7z | tar xf - -C /usr/share/fonts/truetype/
tar -xzf cascadia.tar.gz -C /usr/share/fonts/truetype/
fc-cache

echo "  \e[35m░▒▓█\033[0m copying konqueror profiles & entries"
tar -xzf konqueror.profiles.tar.gz -C $USER_HOME/.trinity/share/apps/
mv $USER_HOME/.trinity/share/apps/konqsidebartng/filemanagement/entries/.version .version  > /dev/null 2>&1
rm -f $USER_HOME/.trinity/share/apps/konqsidebartng/filemanagement/entries/*
mv .version $USER_HOME/.trinity/share/apps/konqsidebartng/filemanagement/entries/.version  > /dev/null 2>&1
tar -xzf konq_fm_entries.tar.gz -C $USER_HOME/.trinity/share/apps/konqsidebartng/filemanagement/entries/
tar -xzf konqueror.profiles.tar.gz -C $USER_HOME/.trinity/share/apps/konqueror/
sudo tar -xzf konqueror.profiles.tar.gz -C /root/.trinity/share/apps/konqueror/



#theme files
echo "  \e[35m░▒▓█\033[0m copying color scheme"
mkdir -p $USER_HOME/.trinity/share/apps/tdedisplay/color-schemes/
sudo mkdir -p /root/.trinity/share/apps/tdedisplay/color-schemes/
if [ $1 -eq 1 ]
then
tar -xzf color-scheme-dark.tar.gz -C $USER_HOME/.trinity/share/apps/tdedisplay/color-schemes/
tar -xzf color-scheme-dark.tar.gz -C /root/.trinity/share/apps/tdedisplay/color-schemes/
else
tar -xzf color-scheme.tar.gz -C $USER_HOME/.trinity/share/apps/tdedisplay/color-schemes/
tar -xzf color-scheme.tar.gz -C /root/.trinity/share/apps/tdedisplay/color-schemes/
fi

echo "  \e[35m░▒▓█\033[0m copying style files"
#\cp twinplastikrc $USER_HOME/.trinity/share/config/twinplastikrc
if [ $1 -eq 1 ]
then
tar -xzf qtcurve_stylerc_dark.tar.gz -C $USER_HOME/.configtde/qtcurve/
tar -xzf qtcurve_stylerc_dark.tar.gz -C /root/.config/qtcurve/
else
tar -xzf qtcurve_stylerc.tar.gz -C $USER_HOME/.configtde/qtcurve/
tar -xzf qtcurve_stylerc.tar.gz -C /root/.config/qtcurve/
fi
tar -xzf tdestylerc.tar.gz -C $USER_HOME/.qt/
tar -xzf tdestylerc.tar.gz -C /etc/tqt3/
tar -xzf qtrc.tar.gz -C $USER_HOME/.qt/
tar -xzf qtrc.tar.gz -C /etc/tqt3/

echo "  \e[35m░▒▓█\033[0m copying sounds"
tar -xzf sounds.tar.gz -C /opt/trinity/share/sounds/
tar -xzf knotify.eventsrc.tar.gz -C $USER_HOME/.trinity/share/config/
#as I don't know yet to modify root apps sound scheme, I delete KDE_Error_x.ogg, because
#sound doesn't seem to work right in root mode (awfull sounding with cracks)
rm -f /opt/trinity/share/sounds/KDE_Error_1.ogg
rm -f /opt/trinity/share/sounds/KDE_Error_2.ogg
rm -f /opt/trinity/share/sounds/KDE_Error_3.ogg
tar -xzf 90-usb.rules.tar.gz -C /etc/udev/rules.d/
#binary
if ( getconf LONG_BIT | grep -q 64 ); then
tar -xzf usb_insert.tar.gz -C /usr/bin/
else
tar -xzf usb_insert_i386.tar.gz -C /etc/udev/rules.d/
fi
udevadm control --reload-rules

echo "  \e[35m░▒▓█\033[0m copying tdm windows theme..."
tar -xzf tdmwin.tar.gz -C /opt/trinity/share/apps/tdm/themes/
echo "  \e[35m░▒▓█\033[0m copying ksplash theme..."
tar -xzf Redmond10.tar.gz -C /opt/trinity/share/apps/ksplash/Themes/

#hide some login msg
touch ~/.hushlogin
echo
echo "${BLUE}----------------------------------------------------------------"
echo "----------------------------------------------------------------${NOCOLOR}"
echo
echo
echo


