#!/bin/sh

#check root
if [ "$(id -u)" -ne 0 ]; then
        echo 'This script must be run by root' >&2
        exit 1
fi
#


USER_HOME=$(eval echo ~${SUDO_USER})


NOCOLOR='\033[0m'
RED='\033[0;31m'
ORANGE='\033[0;33m'
BLUE='\033[0;96m'
SEPL="${ORANGE}════════════════════════════════════════════════════════════════════════════════════════${NOCOLOR}"
echo "${RED}== ${BLUE}\e[1m\e[4mCopying various files...\e[21m"
echo "${SEPL}"
#echo "  \e[35m░▒▓█\033[0m copying start screen image"
#tar -xzf Blacktux-TDE-Classic.tar.gz -C /opt/trinity/share/apps/ksplash/Themes
echo "  \e[35m░▒▓█\033[0m copying icons"
#tar -xzf We10X-icon-theme.tar.gz
#cd We10X-icon-theme/
#./install.sh
#cd ..
if [ $1 -eq 1 ]
then
tar -xzf kdeten_dark.tar.gz -C /usr/share/icons/
gtk-update-icon-cache /usr/share/icons/kdeten_dark/
else
tar -xzf kdeten_light.tar.gz -C /usr/share/icons/
gtk-update-icon-cache /usr/share/icons/kdeten_light/
fi
echo "  \e[35m░▒▓█\033[0m copying cursors"
tar -xzf Windows10Light.tar.gz -C /usr/share/icons/
tar -xzf Windows10Dark.tar.gz -C /usr/share/icons/
echo "  \e[35m░▒▓█\033[0m copying login icon"
\cp tuxlogo.png /opt/trinity/share/apps/tdm/pics/tuxlogo.png

echo "  \e[35m░▒▓█\033[0m copying start menu image"
if [ $1 -eq 1 ]
then
tar -xzf StartHere.png-dark.tar.gz -C /usr/share/pixmaps/
else
tar -xzf StartHere.png.tar.gz -C /usr/share/pixmaps/
fi

echo "  \e[35m░▒▓█\033[0m copying kmenu side image"
if [ $1 -eq 1 ]
then
tar -xzf kside_tile_dark.png.tar.gz -C /opt/trinity/share/apps/kicker/pics/
else
tar -xzf kside_tile.png.tar.gz -C /opt/trinity/share/apps/kicker/pics/
fi

echo "  \e[35m░▒▓█\033[0m copying wallpapers"
tar -xzf q4seb_wallpapers.tar.gz -C /opt/trinity/share/wallpapers/
echo "  \e[35m░▒▓█\033[0m copying font"
tar -xzf Segoe_UI.tar.gz -C /usr/share/fonts/truetype/
echo "  \e[35m░▒▓█\033[0m copying konqueror file management profile & entries"
tar -xzf konq_fm_profile.tar.gz -C $USER_HOME/.trinity/share/apps/konqueror/profiles/
mv $USER_HOME/.trinity/share/apps/konqsidebartng/filemanagement/entries/.version .version
rm -f $USER_HOME/.trinity/share/apps/konqsidebartng/filemanagement/entries/*
mv .version $USER_HOME/.trinity/share/apps/konqsidebartng/filemanagement/entries/.version
tar -xzf konq_fm_entries.tar.gz -C $USER_HOME/.trinity/share/apps/konqsidebartng/filemanagement/entries/

#backup of files to be modified - todo

#theme files
echo "  \e[35m░▒▓█\033[0m copying color scheme"
if [ $1 -eq 1 ]
then
tar -xzf color-scheme-dark.tar.gz -C $USER_HOME/.trinity/share/apps/tdedisplay/color-schemes/
tar -xzf color-scheme-dark.tar.gz -C /root/.trinity/share/apps/tdedisplay/color-schemes/
else
tar -xzf color-scheme.tar.gz -C $USER_HOME/.trinity/share/apps/tdedisplay/color-schemes/
tar -xzf color-scheme.tar.gz -C /root/.trinity/share/apps/tdedisplay/color-schemes/
fi

echo "  \e[35m░▒▓█\033[0m copying style files"
#\cp twinplastikrc $USER_HOME/.trinity/share/config/twinplastikrc
if [ $1 -eq 1 ]
then
tar -xzf qtcurve_stylerc_dark.tar.gz -C $USER_HOME/.configtde/qtcurve/
tar -xzf qtcurve_stylerc_dark.tar.gz -C /root/.config/qtcurve/
else
tar -xzf qtcurve_stylerc.tar.gz -C $USER_HOME/.configtde/qtcurve/
tar -xzf qtcurve_stylerc.tar.gz -C /root/.config/qtcurve/
fi
tar -xzf tdestylerc.tar.gz -C $USER_HOME/.qt/
tar -xzf tdestylerc.tar.gz -C /etc/tqt3/
tar -xzf qtrc.tar.gz -C $USER_HOME/.qt/
tar -xzf qtrc.tar.gz -C /etc/tqt3/


#hide some login msg
touch ~/.hushlogin
echo
echo "${BLUE}----------------------------------------------------------------"
echo "----------------------------------------------------------------${NOCOLOR}"
echo
echo
echo


