#!/bin/sh
#check root
if [ "$(id -u)" -ne 0 ]; then
        echo 'This script must be run by root' >&2
        exit 1
fi
#
NOCOLOR='\033[0m'
RED='\033[0;31m'
ORANGE='\033[0;33m'
BLUE='\033[0;96m'
SEPL="${ORANGE}════════════════════════════════════════════════════════════════════════════════════════${NOCOLOR}"
echo "${RED}== ${BLUE}\e[1m\e[4mInstall grub theme...\e[21m"
echo "${SEPL}"
tar -xzf Xenlism-Debian.tar.gz -C /usr/share/grub/themes
echo "${BLUE}----------------------------------------------------------------"
echo "----------------------------------------------------------------${NOCOLOR}"
echo
echo
echo
