#!/bin/sh
#check root
if [ "$(id -u)" -ne 0 ]; then
        echo 'This script must be run by root' >&2
        exit 1
fi
#
SEPL="════════════════════════════════════════════════════════════════════════════════════════"
echo "== Quiet printk"
echo "${SEPL}"
tar -xzf 20-quiet-printk.conf.tar.gz -C /etc/sysctl.d/
echo "════════════════════════════════════════════════════════════════════════════════"
echo "════════════════════════════════════════════════════════════════════════════════"
echo
echo
echo
echo "== Customizing grub scripts..."
echo "${SEPL}"
tar -xzf grub_linux.tar.gz -C /etc/grub.d/
echo "════════════════════════════════════════════════════════════════════════════════"
echo "════════════════════════════════════════════════════════════════════════════════"
echo
echo
echo

