#!/bin/sh
#check root
if [ "$(id -u)" -ne 0 ]; then
        echo 'This script must be run by root' >&2
        exit 1
fi
#
NOCOLOR='\033[0m'
RED='\033[0;31m'
ORANGE='\033[0;33m'
BLUE='\033[0;96m'
SEPL="${ORANGE}════════════════════════════════════════════════════════════════════════════════════════${NOCOLOR}"
echo "${RED}== ${BLUE}\e[1m\e[4mInstall plymouth theme...\e[21m"
echo "${SEPL}"
#tar -xzf sebtux.tar.gz -C /usr/share/plymouth/themes
#/usr/sbin/plymouth-set-default-theme -R sebtux
tar -xzf q4win10.tar.gz -C /usr/share/plymouth/themes
if ! (/usr/sbin/plymouth-set-default-theme)|grep -q "q4win10" ; then
/usr/sbin/plymouth-set-default-theme -R q4win10
else
echo "plymouth theme q4win10 already set, skipping..."
fi
echo "${BLUE}----------------------------------------------------------------"
echo "----------------------------------------------------------------${NOCOLOR}"
echo
echo
echo
