#!/bin/sh
#check root
if [ "$(id -u)" -ne 0 ]; then
        echo 'This script must be run by root' >&2
        exit 1
fi
#
NOCOLOR='\033[0m'
RED='\033[0;31m'
ORANGE='\033[0;33m'
BLUE='\033[0;96m'
SEPL="${ORANGE}════════════════════════════════════════════════════════════════════════════════════════${NOCOLOR}"
echo "${RED}== ${BLUE}\e[1m\e[4mCustomizing grub parameters\e[21m"
echo "${SEPL}"

#GRUB-DEFAULT
if ! grep -q "GRUB_DEFAULT=" "/etc/default/grub"; then
echo 'GRUB_DEFAULT="0"' | sudo tee -a /etc/default/grub
fi
sudo sed -i '/GRUB_DEFAULT=/c\GRUB_DEFAULT="0"' /etc/default/grub
#GRUB_TIMEOUT_STYLE
if ! grep -q "GRUB_TIMEOUT_STYLE=" "/etc/default/grub"; then
echo 'GRUB_TIMEOUT_STYLE="menu"' | sudo tee -a /etc/default/grub
fi
sudo sed -i '/GRUB_TIMEOUT_STYLE=/c\GRUB_TIMEOUT_STYLE="menu"' /etc/default/grub
#GRUB_TIMEOUT
if ! grep -q "GRUB_TIMEOUT=" "/etc/default/grub"; then
echo 'GRUB_TIMEOUT="5"' | sudo tee -a /etc/default/grub
fi
sudo sed -i '/GRUB_TIMEOUT=/c\GRUB_TIMEOUT="5"' /etc/default/grub
#GRUB_BACKGROUND
if ! grep -q "GRUB_BACKGROUND=" "/etc/default/grub"; then
echo 'GRUB_BACKGROUND="/usr/share/grub/themes/q4os_seb/background.png"' | sudo tee -a /etc/default/grub
fi
sudo sed -i '/GRUB_BACKGROUND=/c\GRUB_BACKGROUND="/usr/share/grub/themes/q4os_seb/background.png"' /etc/default/grub
#GRUB_TERMINAL
sudo sed -i '/GRUB_TERMINAL=/c\#GRUB_TERMINAL="console"' /etc/default/grub
#GRUB_GFXMODE
if ! grep -q "GRUB_GFXMODE=" "/etc/default/grub"; then
echo 'GRUB_GFXMODE="1920x1080,1366x768,1024x768,auto"' | sudo tee -a /etc/default/grub
fi
sudo sed -i '/GRUB_GFXMODE=/c\GRUB_GFXMODE="1920x1080,1366x768,1024x768,auto"' /etc/default/grub
#GRUB_DISABLE_RECOVERY
if ! grep -q "GRUB_DISABLE_RECOVERY=" "/etc/default/grub"; then
echo 'GRUB_DISABLE_RECOVERY="true"' | sudo tee -a /etc/default/grub
fi
sudo sed -i '/GRUB_DISABLE_RECOVERY=/c\GRUB_DISABLE_RECOVERY="true"' /etc/default/grub
#GRUB_THEME
if ! grep -q "GRUB_THEME=" "/etc/default/grub"; then
echo 'GRUB_THEME="/usr/share/grub/themes/q4os_seb/theme.txt"' | sudo tee -a /etc/default/grub
fi
sudo sed -i '/GRUB_THEME=/c\GRUB_THEME="/usr/share/grub/themes/q4os_seb/theme.txt"' /etc/default/grub


#GRUB_CMDLINE_LINUX_DEFAULT
#fbcon
if ! (grep "GRUB_CMDLINE_LINUX_DEFAULT=" "/etc/default/grub")|grep -q "fbcon="; then
sudo sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT="/&fbcon=nodefer /' /etc/default/grub
fi
sudo sed -i 's/fbcon=[0-9]*[a-z]*[A-Z]*/fbcon=nodefer/' /etc/default/grub
#splash
if ! (grep "GRUB_CMDLINE_LINUX_DEFAULT=" "/etc/default/grub")|grep -q "splash"; then
sudo sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT="/&splash /' /etc/default/grub
fi
#loglevel
if ! (grep "GRUB_CMDLINE_LINUX_DEFAULT=" "/etc/default/grub")|grep -q "loglevel="; then
sudo sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT="/&loglevel=0 /' /etc/default/grub
fi
sudo sed -i 's/loglevel=[0-9]*[a-z]*[A-Z]*/loglevel=0/' /etc/default/grub
#rd.udev.log_level
if ! (grep "GRUB_CMDLINE_LINUX_DEFAULT=" "/etc/default/grub")|grep -q "rd.udev.log_level="; then
sudo sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT="/&rd.udev.log_level=0 /' /etc/default/grub
fi
sudo sed -i 's/rd.udev.log_level=[0-9]*[a-z]*[A-Z]*/rd.udev.log_level=0/' /etc/default/grub
#systemd.show_status
if ! (grep "GRUB_CMDLINE_LINUX_DEFAULT=" "/etc/default/grub")|grep -q "systemd.show_status="; then
sudo sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT="/&systemd.show_status=0 /' /etc/default/grub
fi
sudo sed -i 's/systemd.show_status=[0-9]*[a-z]*[A-Z]*/systemd.show_status=0/' /etc/default/grub
#rd.systemd.show_status
if ! (grep "GRUB_CMDLINE_LINUX_DEFAULT=" "/etc/default/grub")|grep -q "rd.systemd.show_status="; then
sudo sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT="/&rd.systemd.show_status=false /' /etc/default/grub
fi
sudo sed -i 's/rd.systemd.show_status=[0-9]*[a-z]*[A-Z]*/rd.systemd.show_status=false/' /etc/default/grub
#vt.cur_default=1
if ! (grep "GRUB_CMDLINE_LINUX_DEFAULT=" "/etc/default/grub")|grep -q "vt.cur_default="; then
sudo sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT="/&vt.cur_default=1 /' /etc/default/grub
fi
sudo sed -i 's/vt.cur_default=[0-9]*[a-z]*[A-Z]*/vt.cur_default=1/' /etc/default/grub


sudo update-grub
sudo sed -i 's/echo/#ech~o/g' /boot/grub/grub.cfg
echo "${BLUE}----------------------------------------------------------------"
echo "----------------------------------------------------------------${NOCOLOR}"
echo
echo
echo
