#!/bin/bash
LIGHTGRAY='\033[0;37m';GRAY='\033[0;90m'
NOCOLOR='\033[0m';RED='\033[0;31m'
REDL='\033[0;91m';ORANGE='\033[0;33m'
BLUE='\033[0;96m';LIGHTGREEN='\033[1;32m'
YELLOW='\033[0;93m';WHITE='\033[0;97m'
SEPL="${ORANGE}";for ((i = 0; i < 80; i++)); do  SEPL+="═";done;SEPL+="${NOCOLOR}"

begin () {
wmctrl -r :ACTIVE: -N "$1"
echo -e "${LIGHTGRAY} "
echo -e "$(cat common/title)"
echo
echo -en "  "
for i in {16..21} {21..16} ; do echo -en "\e[48;5;${i}m \e[0m\e[48;5;${i}m \e[0m\e[48;5;${i}m \e[0m" ; done ;
echo -en "\e[97m\e[1;4m$1\e[21m${LIGHTGRAY} "
for i in {16..21} {21..16} ; do echo -en "\e[48;5;${i}m \e[0m\e[48;5;${i}m \e[0m\e[48;5;${i}m \e[0m" ; done ;
echo -e "${NOCOLOR}"
echo

case "$1" in
  "Help Qtheme") echo -e "$(cat common/doc.qtheme)"; echo -e "$(cat common/atyourownrisk)";;
  "Help Qapps") echo -e "$(cat common/doc.qapps)" ;;
  "Help Qperfs") echo -e "$(cat common/doc.qperfs)";echo -e "$(cat common/atyourownrisk)" ;;
  "Help Qlaptop") echo -e "$(cat common/doc.qlaptop)";echo -e "$(cat common/atyourownrisk)";;
  "Help Qkids") ;;
  *) ;;
esac

if [ -z "$2" ]; then 
opt=0
else
if [ $2 = "backup" ]; then
opt=1
fi
fi

#user home
USER_HOME=$(eval echo ~${SUDO_USER})
if ( getconf LONG_BIT | grep -q 64 ); then
bits="64bits system";
else  bits="32bits system"; fi

if [ $opt -eq 0 ]; then
#test $TDEHOME
if [ -z "$TDEHOME" ]
then
      echo -e "          ${RED}^-^"
      echo -e "         (x X)${GRAY}"
      echo -e "   ══${RED}ooO${GRAY}══${RED}(_)${GRAY}══${RED}Ooo${GRAY}══════ ${NOCOLOR}Error :-( ${GRAY}════════${NOCOLOR}"
      echo "   \$TDEHOME is empty, cannot continue"
      echo -en "\033]0;$script - Error\a"
      echo
      read -p "Press enter..."
      echo
      exit
else
      echo -e "  ${LIGHTGRAY}█${NOCOLOR} User Home is ${ORANGE}$USER_HOME ${NOCOLOR}"
      echo -e "  ${GRAY}█${NOCOLOR} TDEHOME is ${ORANGE}$TDEHOME ${NOCOLOR} / ${BLUE}▒ $bits${NOCOLOR}"
               if [[ $dark -eq 1 ]]
               then
                echo -e "  ${BLUE}█${NOCOLOR} Dark theme selected"
               fi
               if [[ $installall -eq 1 ]]
               then
                echo -e "  ${LIGHTGREEN}█${NOCOLOR} Install everything whithout asking"
               fi
      echo
fi
echo -e "          ${LIGHTGREEN}^-^"
echo -e "         (o o)${GRAY}"
echo -e "   ══${LIGHTGREEN}ooO${GRAY}══${LIGHTGREEN}(_)${GRAY}══${LIGHTGREEN}Ooo${GRAY}══════ ${NOCOLOR}Ready :-) ${GRAY}════════${NOCOLOR}"
else
echo -e "         ${GRAY}     █████                                                    "          
echo -e "             ██${REDL}▒▒▒${GRAY}██                                                    "        
echo -e "             ██${REDL}▒▒▒${GRAY}██                                                      "      
echo -e "        ███████${REDL}▒▒▒${GRAY}███████     "
echo -e "        █${REDL}▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒${GRAY}█     "
echo -e "        ███████${REDL}▒▒▒${GRAY}███████    ${WHITE}___${GRAY}"
echo -e "             ██${REDL}▒▒▒${GRAY}██        ${WHITE}<_${REDL}╋${WHITE}_>                                               "          
echo -e "             ${GRAY}██${REDL}▒▒▒${GRAY}██        ${WHITE}(o o)${GRAY}                                                   "         
echo -e "              ${GRAY}█████   ══${WHITE}ooO${GRAY}══${WHITE}(_)${GRAY}══${WHITE}Ooo${GRAY}══════ ${NOCOLOR}Ready :-) ${GRAY}════════${NOCOLOR}    "
echo
fi
echo -en "\e[5m   Press enter to start (or esc to quit) \e[25m"
read -s -n1 key
 case $key in
     $'\e') echo;printf '\e[A\e[K';echo;wmctrl -r :ACTIVE: -b remove,maximized_vert,maximized_horz;exit 2;;
 esac
echo
printf '\e[A\e[K'
echo
echo
}

