#!/bin/bash
LIGHTGRAY='\033[0;37m'
GRAY='\033[0;90m'
NOCOLOR='\033[0m'
RED='\033[0;31m'
REDL='\033[0;91m'
ORANGE='\033[0;33m'
BLUE='\033[0;96m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[0;93m'
WHITE='\033[0;97m'
SEPL="${ORANGE}════════════════════════════════════════════════════════════════════════════════════════${NOCOLOR}"


begin () {
wmctrl -r :ACTIVE: -b add,maximized_vert,maximized_horz
wmctrl -r :ACTIVE: -N "$1"
echo -e "${LIGHTGRAY} "
echo -e "$(cat common/title)"
echo
echo -en "  "
for i in {16..21} {21..16} ; do echo -en "\e[48;5;${i}m \e[0m\e[48;5;${i}m \e[0m\e[48;5;${i}m \e[0m" ; done ;
echo -en "\e[97m\e[1;4m$1\e[21m${LIGHTGRAY} "
for i in {16..21} {21..16} ; do echo -en "\e[48;5;${i}m \e[0m\e[48;5;${i}m \e[0m\e[48;5;${i}m \e[0m" ; done ;
echo -e "${NOCOLOR}"
echo
if [ -z "$2" ]; then
opt=0
else
if [ $2 = "backup" ]; then
opt=1
fi
fi

if [ $opt -eq 0 ]; then
#user home
USER_HOME=$(eval echo ~${SUDO_USER})
#test $TDEHOME
if [ -z "$TDEHOME" ]
then
      echo -e "          ${RED}^-^"
      echo -e "         (x X)${GRAY}"
      echo -e "   ══${RED}ooO${GRAY}══${RED}(_)${GRAY}══${RED}Ooo${GRAY}══════ ${NOCOLOR}Error :-( ${GRAY}════════${NOCOLOR}"
      echo "   \$TDEHOME is empty, cannot continue"
      echo -en "\033]0;$script - Error\a"
      echo
      read -p "Press enter..."
      echo
      wmctrl -r :ACTIVE: -b remove,maximized_vert,maximized_horz
      exit
else
      echo -e "  ${LIGHTGRAY}█${NOCOLOR} User Home is ${ORANGE}$USER_HOME ${NOCOLOR}"
      echo -e "  ${GRAY}█${NOCOLOR} TDEHOME is ${ORANGE}$TDEHOME ${NOCOLOR}"
               if [[ $dark -eq 1 ]]
               then
                echo -e "  ${BLUE}█${NOCOLOR} Dark theme selected"
               fi
               if [[ $interact -eq 1 ]]
               then
                echo -e "  ${LIGHTGREEN}█${NOCOLOR} Interactive Mode"
               fi
      echo
fi
echo -e "          ${LIGHTGREEN}^-^"
echo -e "         (o o)${GRAY}"
echo -e "   ══${LIGHTGREEN}ooO${GRAY}══${LIGHTGREEN}(_)${GRAY}══${LIGHTGREEN}Ooo${GRAY}══════ ${NOCOLOR}Ready :-) ${GRAY}════════${NOCOLOR}"
else
echo -e "         ${GRAY}     █████                                                    "          
echo -e "             ██${REDL}▒▒▒${GRAY}██                                                    "        
echo -e "             ██${REDL}▒▒▒${GRAY}██                                                      "      
echo -e "        ███████${REDL}▒▒▒${GRAY}███████     "
echo -e "        █${REDL}▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒${GRAY}█     "
echo -e "        ███████${REDL}▒▒▒${GRAY}███████    ${WHITE}___${GRAY}"
echo -e "             ██${REDL}▒▒▒${GRAY}██        ${WHITE}<_${REDL}╋${WHITE}_>                                               "          
echo -e "             ${GRAY}██${REDL}▒▒▒${GRAY}██        ${WHITE}(o o)${GRAY}                                                   "         
echo -e "              ${GRAY}█████   ══${WHITE}ooO${GRAY}══${WHITE}(_)${GRAY}══${WHITE}Ooo${GRAY}══════ ${NOCOLOR}Ready :-) ${GRAY}════════${NOCOLOR}    "
echo
fi
echo -en "\e[5m   Press enter to start . . .\e[25m"
read -p " "
printf '\e[A\e[K'
echo
echo
}

