#!/bin/bash
progress () {
blockdone="██";blockleft="░░";bar=""
doneparts=$(expr $2 / 5)
for ((i=1;i<=$doneparts;i++)); do bar+=$blockdone ; done ;
left=$(expr 20 - $doneparts)
for ((i=1;i<=$left;i++)) ; do bar+=$blockleft ; done ;
bar+=" ";prog='Progress'
if (($2<10)); then prog+="   "; fi
if (($2<100)) && (($2>9)); then prog+="  "; fi
if (($2==100)); then prog+=" "; fi
prog+="$2% "
echo -en "\033]0;$1 - $prog$bar\a"
}

rotta=1
rotsp="/-\|"
rota () {
printf "\b${rotsp:rotta++%${#rotsp}:1}"
}


itemdisp ()
{
echo -e "${RED}=== ${BLUE}\e[1m\e[4m$1\e[21m"
echo -e "${SEPL}"
}
line1 ()
{ echo
for i in 21 27 33 39 45 51 50 49 48 47 46 82 118 154 190 226 220 214 208 202 196 197 198 199 200 201 165 129 93 57 21
do echo -en "\e[48;5;${i}m \e[0m"; done }
line2 ()
{ for i in 21 27 33 39 45 51 50 49 48 47 46 82 118 154 190 226 220 214 208 202 196 197 198 199 200 201 165 129 93 57 21
do echo -en "\e[48;5;${i}m \e[0m" ; done }

sep ()
{ echo -e "${BLUE}════════════════════════════════════════════════════════════════"
         echo -e "════════════════════════════════════════════════════════════════${NOCOLOR}"
}

alldone()
{
line1;echo -en " ┏┓┓ ┓   ┳┓┏┓┳┓┏┓ ";line2
line1;echo -en " ┣┫┃ ┃   ┃┃┃┃┃┃┣  ";line2
line1;echo -en " ┛┗┗┛┗┛  ┻┛┗┛┛┗┗┛ ";line2
echo
echo
read -p "Press enter..."
echo
}
