#!/bin/bash
Xres=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)
Yres=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2)
if (( $Yres < 800 )); then wh=580;wl=750; else wh=720;wl=1000; fi
xpos=$((($Xres-$wl)/2));ypos=$((($Yres-$wh)/2))
wmctrl -r :ACTIVE: -e 0,$xpos,$ypos,$wl,$wh > /dev/null 2>&1
if [ $? -ne 0 ]; then
echo -ne '\e[8;32;95t'
fi
sleep 0.25
