#!/bin/sh
Xres=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)
Yres=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2)
if (( $Yres < 800 )); then
wh=580;wl=800
else
wh=700;wl=1000
fi
xpos=$((($Xres-$wl)/2));ypos=$((($Yres-$wh)/2))
wmctrl -r :ACTIVE: -e 0,$xpos,$ypos,$wl,$wh
sleep 0.25