#!/bin/bash
export NEWT_COLORS='
root=,brown
window=,lightgray
border=white,lightgray
textbox=white,blue
button=black,white
actbutton=black,white
title=black,lightgray
'
#============================================================================

#============================================================================
#============================= MAIN =========================================
while [ 1 ]
do
ret=$(TERM=ansi whiptail --title "-=- Q4OS Seb Scripts -=-" --menu "                    Qtools Scripts - Grub tools" 25 70 15 "»boot menu" "   [      enable/disable boot menu      ]" "»Default entry" "   [           Set default entry        ]" "»Timeout" "   [            set menu timeout        ]" "»Other OS" "   [   Enable/disable other OS choice   ]" "»UEFI" "   [     Enable/disable UEFI option     ]" "»Command line" "   [       Modify boot command line     ]" "«exit" "   [          <- quit this menu         ]" 3>&1 1>&2 2>&3)

echo
case $ret in
"»Timeout")   
        settimeout
;;
"«exit") exit
;;
esac
done

